name: Terraform - Controls

on:
  push:
    branches: [main]
    paths:
      - "controls/**"
  pull_request:
    branches: [main]
    paths:
      - "controls/**"

permissions:
  id-token: write
  contents: read

jobs:
  controls:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./controls

    env:
      AWS_REGION: us-east-1

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::495013528126:role/GithubTerraformControlsRole
          aws-region: ${{ env.AWS_REGION }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - run: terraform init
      - run: terraform fmt -check
      - run: terraform plan -input=false

      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -input=false -auto-approve
